# permissions for end users to edit interloks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: interlok-editor-role
rules:
- apiGroups:
  - intergrations.proagrica.com
  resources:
  - interloks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intergrations.proagrica.com
  resources:
  - interloks/status
  verbs:
  - get
