
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - intergrations.proagrica.com
  resources:
  - interloks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intergrations.proagrica.com
  resources:
  - interloks/finalizers
  verbs:
  - update
- apiGroups:
  - intergrations.proagrica.com
  resources:
  - interloks/status
  verbs:
  - get
  - patch
  - update
